description: Color Printer Func for Python
name: ColorPrinter
version: 1.2.0
updated_date: 2024-10-26
author: OnieMikel
author_email: 
url: https://github.com/oniemikel/ColorPrinter-for-Python
license: BSD 3-Clause
download_url: 
python_requires: '>=3.11'
